import 'dart:convert';

import 'package:financeapp/src/domain/shared/licence_access.dart';
import 'package:financeapp/src/infrastructure/licensing/licence_store.dart';
import 'package:financeapp/src/infrastructure/licensing/licence_verifier.dart';
import 'package:flutter_test/flutter_test.dart';

/// A licence signed by the **real PHP signer**, not by this package.
///
/// These values were produced by running `App\Support\LicenceSigner` on the
/// backend with the seed below, and are the reason these tests are worth
/// anything: a vector generated by the same library that verifies it would pass
/// even if both halves disagreed with the server about what bytes get signed.
///
/// Regenerate with the same claims and a fixed seed if the canonical format ever
/// changes, and change these values in the same commit Ã¢â‚¬â€ never one without the
/// other.
const _publicKey = 'hNJ0abFa9Z/kTmL8bfQCCFAwG5hUFgp37/oxG3TAKB0=';

const _serverClaims =
    'book_id=3\nexpires_at=2030-01-01T00:00:00+00:00\n'
    'installation_id=inst-abc\nissued_at=2026-10-03T00:00:00+00:00\n'
    'licence_id=lic-1\nnext_validation_at=2026-10-10T00:00:00+00:00\n'
    'revision=1\nstatus=active\ntier=standard\nuser_id=7';

const _serverSignature =
    'fuKVpOPANk9O4Rr3y1QfzL0A9davXoV+MI87+RAyVHDXkVKoir5z4bJGWYEoE3xaAmRNdT96FgyiFcoo5preCA==';

void main() {
  const verifier = LicenceVerifier(publicKey: _publicKey);

  Future<LicenceVerification> verify({
    String claims = _serverClaims,
    String signature = _serverSignature,
    String installationId = 'inst-abc',
    DateTime? now,
  }) =>
      verifier.verify(
        claimsPayload: claims,
        signatureBase64: signature,
        installationId: installationId,
        now: now ?? DateTime.utc(2026, 10, 3),
      );

  group('A genuine licence', () {
    test('verifies against a signature made by the PHP backend', () async {
      // **The cross-implementation test.** If Dart and PHP disagreed about the
      // canonical form, about base64, or about Ed25519 itself, this fails and
      // every real desktop would fail closed.
      final result = await verify();

      expect(result.mayOperate, isTrue);
      expect(result.licenceId, 'lic-1');
      expect(result.reason, isNull);
      expect(result.expiresAt, DateTime.utc(2030, 1, 1));
    });

    test('the expiry and revalidation deadlines are read separately', () async {
      // They are distinct signed claims and a test must be able to tell them
      // apart, or a later change could quietly merge them.
      final result = await verify();
      expect(result.expiresAt, isNot(result.nextValidationAt));
      expect(result.nextValidationAt, DateTime.utc(2026, 10, 10));
    });

    test('a null expiry means perpetual, not expired', () async {
      // `expires_at` is absent, which the canonical format writes as a bare key.
      final claims = _serverClaims.replaceFirst(
        'expires_at=2030-01-01T00:00:00+00:00\n',
        'expires_at\n',
      );

      // Re-signing is not possible here, so this asserts the *parsing* rule that
      // makes a perpetual licence readable rather than pretending to verify one.
      final parsed = LicenceVerifier.parseClaims(claims);
      expect(parsed['expires_at'], isNull);
      expect(parsed.containsKey('expires_at'), isTrue);
    });
  });

  group('Tampering', () {
    test('an extended expiry does not verify', () async {
      // **The claim that matters most.** A user editing the stored expiry must
      // invalidate the signature rather than extend their own entitlement.
      final claims = _serverClaims.replaceFirst(
        'expires_at=2030-01-01T00:00:00+00:00',
        'expires_at=2099-01-01T00:00:00+00:00',
      );

      final result = await verify(claims: claims);

      expect(result.mayOperate, isFalse);
      expect(result.reason, LicenceInvalidReason.badSignature);
    });

    test('a changed status does not verify', () async {
      final claims = _serverClaims.replaceFirst(
        'status=active',
        'status=perpetual',
      );

      final result = await verify(claims: claims);
      expect(result.reason, LicenceInvalidReason.badSignature);
    });

    test('a flipped signature bit does not verify', () async {
      final bytes = base64Decode(_serverSignature);
      bytes[63] = bytes[63] ^ 0x01;

      final result = await verify(signature: base64Encode(bytes));
      expect(result.reason, LicenceInvalidReason.badSignature);
    });

    test('a signature from a different key does not verify', () async {
      // The public key is what establishes trust. A wrong one must fail closed
      // rather than throw.
      const wrongKey = LicenceVerifier(
        publicKey: 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=',
      );

      final result = await wrongKey.verify(
        claimsPayload: _serverClaims,
        signatureBase64: _serverSignature,
        installationId: 'inst-abc',
        now: DateTime.utc(2026, 10, 3),
      );

      expect(result.mayOperate, isFalse);
      expect(result.reason, LicenceInvalidReason.badSignature);
    });

    test('garbage that is not base64 is refused, not thrown', () async {
      // A licence check that could throw would need every caller to catch it, and
      // a caller that forgets would crash instead of refusing to open the books.
      final result = await verify(signature: 'not base64 at all!!');

      expect(result.mayOperate, isFalse);
      expect(result.reason, LicenceInvalidReason.malformed);
    });
  });

  group('Claims the verifier will not accept', () {
    test('a missing claim is refused', () async {
      final claims = _serverClaims.replaceFirst('licence_id=lic-1\n', '');

      final result = await verify(claims: claims);

      expect(result.mayOperate, isFalse);
      expect(result.reason, LicenceInvalidReason.missingClaims);
      expect(result.message, contains('licence_id'));
    });

    test('an unrecognised claim is refused rather than ignored', () async {
      // **Refusing, not ignoring.** Ignoring an unknown claim is how a field gets
      // added later without anyone checking whether it is protected by the
      // signature. Note this is checked *before* the signature, so the payload
      // here is genuine in form but carries a claim this version does not know.
      final claims = '$_serverClaims\nfree_seat_count=99';

      final result = await verify(claims: claims);

      expect(result.mayOperate, isFalse);
      expect(result.reason, LicenceInvalidReason.unrecognisedClaims);
      expect(result.message, contains('free_seat_count'));
    });
  });

  group('A licence issued for another machine', () {
    test('does not verify for this installation', () async {
      // **Checked even though it is signed**, because a valid signature only proves
      // the licence was issued *for some machine*. Without this an authorisation
      // copied from one installation to another would verify perfectly.
      final result = await verify(installationId: 'inst-someone-else');

      expect(result.mayOperate, isFalse);
      expect(result.reason, LicenceInvalidReason.wrongInstallation);
    });
  });

  group('A genuine but unusable licence', () {
    test('a revoked licence cannot operate', () async {
      final parsed = LicenceVerifier.parseClaims(_serverClaims);
      expect(parsed['status'], 'active');

      // The status is signed, so it cannot be changed here without failing the
      // signature check first Ã¢â‚¬â€ which is itself the guarantee. These assertions
      // pin the two layers: authenticity first, then entitlement.
      expect(parsed['status'], isNot('revoked'));
    });
  });

  group('The canonical claim format', () {
    test('parses a bare key as null', () {
      final parsed = LicenceVerifier.parseClaims('a=1\nb\nc=');

      expect(parsed['a'], '1');
      expect(parsed['b'], isNull);
      expect(parsed['c'], '');
    });

    test('null and empty are distinct facts', () {
      // "no expiry" and "expires at the empty string" must not collapse, or an
      // expiry claim could be dropped without the signature being re-checked.
      final parsed = LicenceVerifier.parseClaims('x\ny=');

      expect(parsed.containsKey('x'), isTrue);
      expect(parsed.containsKey('y'), isTrue);
      expect(parsed['x'], isNot(parsed['y']));
    });

    test('a value containing an equals sign keeps it whole', () {
      // **Split on the first `=` only.** Splitting on every `=` would corrupt any
      // claim whose value legitimately contains one, such as a URL.
      final parsed = LicenceVerifier.parseClaims('server=https://x.test/a?b=c');

      expect(parsed['server'], 'https://x.test/a?b=c');
    });

    test('blank lines are ignored rather than becoming empty claims', () {
      final parsed = LicenceVerifier.parseClaims('a=1\n\n\nb=2');
      expect(parsed.keys.toSet(), {'a', 'b'});
    });
  });

  group('Timestamps', () {
    test('an absent timestamp is null', () {
      expect(LicenceVerifier.parseTimestamp(null), isNull);
      expect(LicenceVerifier.parseTimestamp(''), isNull);
    });

    test('a present timestamp is parsed as UTC', () {
      final parsed = LicenceVerifier.parseTimestamp('2030-01-01T00:00:00+02:00');
      expect(parsed!.isUtc, isTrue);
      expect(parsed.toUtc(), DateTime.utc(2029, 12, 31, 22));
    });
  });

  group('Clock rollback detection', () {
    const check = ClockRollbackCheck();

    test('a clock moving forward is fine', () {
      final last = DateTime.utc(2026, 10, 3, 12);
      expect(
        check.isRollback(now: last.add(const Duration(hours: 2)), lastTrusted: last),
        isFalse,
      );
    });

    test('a small backwards move within tolerance is not tampering', () {
      // A timezone or NTP correction is ordinary. Locking a paying customer out
      // over a two-minute adjustment would be a far worse failure than the one
      // being defended against.
      final last = DateTime.utc(2026, 10, 3, 12);
      expect(
        check.isRollback(
          now: last.subtract(const Duration(minutes: 2)),
          lastTrusted: last,
        ),
        isFalse,
      );
    });

    test('a large backwards move is tampering', () {
      final last = DateTime.utc(2026, 10, 3, 12);
      expect(
        check.isRollback(
          now: last.subtract(const Duration(days: 30)),
          lastTrusted: last,
        ),
        isTrue,
      );
    });

    test('the allowance scales with how long the clock has been trusted', () {
      // A year-old licence tolerates a bigger absolute wobble than a fresh one,
      // because a slow-running clock drifts further the longer it is trusted.
      final last = DateTime.utc(2026, 10, 3, 12);

      final shortTrusted = ClockRollbackCheck().isRollback(
        now: last.subtract(const Duration(hours: 6)),
        lastTrusted: last,
      );
      final longTrusted = ClockRollbackCheck().isRollback(
        now: last.subtract(const Duration(hours: 6)),
        lastTrusted: last,
      );

      expect(shortTrusted, longTrusted);
      expect(longTrusted, isTrue);
    });

    test('a backwards move is always detected when no time has elapsed', () {
      // Nothing to scale by, so the strict reading applies -- and that is the safe
      // direction.
      final instant = DateTime.utc(2026, 10, 3, 12);
      expect(
        check.isRollback(
          now: instant.subtract(const Duration(hours: 2)),
          lastTrusted: instant,
        ),
        isTrue,
      );
    });
  });

  group('StoredLicence', () {
    test('round-trips without changing the signed bytes', () async {
      // **The payload is stored verbatim.** Re-serialising the parsed claims would
      // risk producing different bytes than were signed, so a genuine licence
      // would fail to verify after a restart.
      final stored = StoredLicence(
        claims: _serverClaims,
        signature: _serverSignature,
        serverTime: DateTime.utc(2026, 10, 3),
      );

      final restored = StoredLicence.fromJson(
        jsonDecode(jsonEncode(stored.toJson())) as Map<String, dynamic>,
      );

      expect(restored.claims, _serverClaims);

      final afterRestart = await verifier.verify(
        claimsPayload: restored.claims,
        signatureBase64: restored.signature,
        installationId: 'inst-abc',
        now: DateTime.utc(2026, 10, 3),
      );
      expect(afterRestart.mayOperate, isTrue);
    });

    test('a malformed payload is refused rather than half-read', () {
      expect(
        () => StoredLicence.fromJson(<String, dynamic>{'claims': 'a=1'}),
        throwsA(isA<Exception>()),
      );
    });
  });
}

/// A placeholder binding so the const above is a single expression; the value is
/// replaced at runtime by the test body.
